In [1]:
# python
import os
import math
import csv

# random
import random
#data analysis libraries
import numpy as np
import pandas as pd

# machine learning
import sklearn

# deep learning
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split

# For plotting learning curve
from torch.utils.tensorboard import SummaryWriter

# graph deep learning
import torch_geometric
import networkx as nx

#visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import torch_geometric
%matplotlib inline

# For Progress Bar
from tqdm import tqdm

#ignore warnings
import warnings

warnings.filterwarnings('ignore')

# auto load change
%load_ext autoreload
%autoreload 2

In [2]:
from Data.generate_data import get_and_normalize_data, get_singel_step_data

sequences_x, sequences_y, metrics, edge_index = get_singel_step_data()

In [8]:
sequences_x.shape

(3186, 7, 50, 30)

In [23]:
sequences_x[1, :, 0, :]

array([[-0.15583633, -0.12045782, -0.11900807, -0.11641713, -0.31943093,
        -1.138788  , -0.10927167, -0.34482179, -0.14896192, -0.61539147,
        -0.10044126, -0.04570378, -0.32103572, -0.14437434, -0.1130635 ,
        -0.31763828, -0.43827255, -0.27633023, -0.15657084, -0.15148976,
        -0.34217612, -0.33817347, -0.11919587, -0.12064781, -0.31254395,
        -0.07167629, -0.4056344 , -0.30136405, -0.08923478, -0.30647863],
       [ 3.16900469,  3.16900469,  3.16900469,  3.16900469,  3.16900469,
         3.16921799,  3.16900469,  3.16900469,  3.16900469,  3.16900469,
         3.16900469,  3.16900469,  3.16900469,  3.16900469,  3.16900469,
         3.16900469,  3.16900469,  3.16900469,  3.16900469,  3.16900469,
         3.16900469,  3.16900469,  3.16900469,  3.16900469,  3.16900469,
         3.16921799,  3.16900469,  3.16921799,  3.16740493,  3.16761823],
       [-0.86639817, -0.86010422, -0.86620216, -0.85169296, -0.87007406,
        -0.85528326, -0.85428911, -0.8541049 , -0

In [32]:
from Data.generate_data import generate_data

train_loader, valid_loader, test_loader, edge_index = generate_data()

(4340, 7, 50, 30)


2592

## test x, y shape
+ x: (3187, 30, 50, 6)
+ y: (3187, 30, 50, 1)


In [74]:
x.shape

(3187, 6, 50, 30)

In [76]:
x[0, :, 0, 0]

array([-0.24398395,  3.01788125, -0.86853948, -0.5574395 ,  0.37395689,
       -1.30260131])

In [72]:
from Data.generate_data import get_and_normalize_data

df = get_and_normalize_data('./DatasetUpdate/MMS.csv')

In [65]:
df

pod    adservice-76469b5944-9tlwk                                      \
metric                CpuUsage(m) MemoryUsage(Mi) NetworkReceiveBytes   
0                       -0.149569        3.169005           -0.865079   
1                       -0.155836        3.169005           -0.866398   
2                       -0.120458        3.169005           -0.860104   
3                       -0.119008        3.169005           -0.866202   
4                       -0.116417        3.169005           -0.851693   
...                           ...             ...                 ...   
4363                     0.050429        2.972448           -0.658320   
4364                     0.084544        2.972448           -0.653984   
4367                    -0.567262        2.972448           -0.736490   
4368                    -0.228262        2.970742           -0.726690   
4369                    -0.022272        2.970742           -0.720676   

pod                                                                           \
metric NetworkTransmitBytes PodLatency(s) PodSuccessRate(%) PodWorkload(Ops)   
0                 -0.541802     -0.266415         -0.325425        -1.307591   
1                 -0.557715     -0.266367         -0.846782        -1.272644   
2                 -0.561757     -0.266419         -0.284285        -1.292588   
3                 -0.562050     -0.266357         -0.942526        -1.292605   
4                 -0.549667     -0.266365         -0.869388        -1.277437   
...                     ...           ...               ...              ...   
4363              -0.474146     -0.266271         -0.127093        -0.544091   
4364              -0.468005     -0.266317         -0.127093        -0.544091   
4367              -0.509701     -0.266212         -0.355833        -0.858467   
4368              -0.501013     -0.266307         -0.374426        -0.764020   
4369              -0.487382     -0.266403          0.049083        -0.773635   

pod    adservice-76469b5944-h6cqg                                      ...  \
metric                CpuUsage(m) MemoryUsage(Mi) NetworkReceiveBytes  ...   
0                       -0.243984        3.017881           -0.868539  ...   
1                       -0.404297        3.017668           -0.868504  ...   
2                       -0.287610        3.017881           -0.869992  ...   
3                       -0.237696        3.017881           -0.868161  ...   
4                       -0.221103        3.017668           -0.864126  ...   
...                           ...             ...                 ...  ...   
4363                    -0.171453        3.200253           -0.662942  ...   
4364                     0.027819        3.200040           -0.668054  ...   
4367                    -0.362398        3.200253           -0.736737  ...   
4368                    -0.098033        3.200040           -0.715737  ...   
4369                    -0.369245        3.200040           -0.718215  ...   

pod    shippingservice-7499794f94-gmcld                                     \
metric                    PodLatency(s) PodSuccessRate(%) PodWorkload(Ops)   
0                             -0.253859          0.373957        -1.252704   
1                             -0.264830          0.373957        -1.267654   
2                             -0.232834          0.373957        -1.322530   
3                             -0.238634          0.373957        -1.357476   
4                             -0.260673          0.373957        -1.327374   
...                                 ...               ...              ...   
4363                          -0.250234          0.373957        -0.539100   
4364                          -0.249405          0.373957        -0.574031   
4367                          -0.254169          0.373957        -0.838317   
4368                          -0.249871          0.373957        -0.863776   
4369                          -0.251684          0.373957 

In [63]:
assert x[0][0][1, 2] == df.iloc[0, 9]
assert y[0][0][1] == df.iloc[0, 11]

In [44]:
from Data.DataSet import Dataset

data = Dataset(x, y)

In [5]:
from graph_lstm_vae_ad_ver6 import GraphLSTM_VAE_AD

lstm = GraphLSTM_VAE_AD()
train_loader, valid_loader, test_loader = lstm.get_train_valid_test(data, 50)

In [6]:
for x, y in train_loader:
    print(x.shape)

In [30]:
from Data.generate_data import generate_data, get_data, get_and_normalize_data

train_loader, valid_loader, test_loader, edge_index = generate_data(50)

In [32]:
for x, y in train_loader:
    print(y)

tensor([[[[-0.2664],
          [-0.2661],
          [-0.2658],
          ...,
          [-0.2167],
          [-0.2415],
          [-0.2655]],

         [[-0.2665],
          [-0.2663],
          [-0.2663],
          ...,
          [-0.1780],
          [-0.2435],
          [-0.2383]],

         [[-0.2663],
          [-0.2664],
          [-0.2657],
          ...,
          [-0.1889],
          [-0.2319],
          [-0.2366]],

         ...,

         [[-0.2662],
          [-0.2662],
          [-0.2649],
          ...,
          [-0.2038],
          [-0.2512],
          [-0.2423]],

         [[-0.2664],
          [-0.2664],
          [-0.2657],
          ...,
          [-0.1660],
          [-0.2415],
          [-0.2662]],

         [[-0.2663],
          [-0.2663],
          [-0.2647],
          ...,
          [-0.2196],
          [-0.2437],
          [-0.2367]]],


        [[[-0.2664],
          [-0.2664],
          [-0.2642],
          ...,
          [-0.2159],
          [-0.2317],
     

In [8]:
len(edge)

2

In [14]:
edges

[(0, 21),
 (0, 22),
 (0, 23),
 (0, 24),
 (0, 25),
 (0, 26),
 (1, 21),
 (1, 22),
 (1, 23),
 (1, 24),
 (1, 25),
 (1, 26),
 (2, 21),
 (2, 22),
 (2, 23),
 (2, 24),
 (2, 25),
 (2, 26),
 (3, 21),
 (3, 22),
 (3, 23),
 (3, 24),
 (3, 25),
 (3, 26),
 (21, 0),
 (21, 1),
 (21, 2),
 (21, 3),
 (22, 0),
 (22, 1),
 (22, 2),
 (22, 3),
 (23, 0),
 (23, 1),
 (23, 2),
 (23, 3),
 (24, 0),
 (24, 1),
 (24, 2),
 (24, 3),
 (25, 0),
 (25, 1),
 (25, 2),
 (25, 3),
 (26, 0),
 (26, 1),
 (26, 2),
 (26, 3),
 (4, 21),
 (4, 22),
 (4, 23),
 (4, 24),
 (4, 25),
 (4, 26),
 (5, 21),
 (5, 22),
 (5, 23),
 (5, 24),
 (5, 25),
 (5, 26),
 (6, 21),
 (6, 22),
 (6, 23),
 (6, 24),
 (6, 25),
 (6, 26),
 (7, 21),
 (7, 22),
 (7, 23),
 (7, 24),
 (7, 25),
 (7, 26),
 (8, 21),
 (8, 22),
 (8, 23),
 (8, 24),
 (8, 25),
 (8, 26),
 (9, 21),
 (9, 22),
 (9, 23),
 (9, 24),
 (9, 25),
 (9, 26),
 (21, 4),
 (21, 5),
 (21, 6),
 (21, 7),
 (21, 8),
 (21, 9),
 (22, 4),
 (22, 5),
 (22, 6),
 (22, 7),
 (22, 8),
 (22, 9),
 (23, 4),
 (23, 5),
 (23, 6),
 (23, 7),


In [15]:
G = nx.DiGraph()

In [16]:
G.add_edges_from(edges)

In [18]:
G.edges

OutEdgeView([(0, 21), (0, 22), (0, 23), (0, 24), (0, 25), (0, 26), (21, 0), (21, 1), (21, 2), (21, 3), (21, 4), (21, 5), (21, 6), (21, 7), (21, 8), (21, 9), (21, 12), (21, 13), (21, 14), (21, 15), (21, 16), (21, 17), (21, 18), (21, 19), (21, 10), (21, 11), (21, 29), (21, 30), (21, 31), (21, 32), (21, 33), (21, 34), (21, 35), (21, 36), (21, 37), (21, 38), (21, 39), (21, 40), (21, 41), (21, 42), (21, 43), (21, 48), (21, 49), (21, 44), (21, 45), (21, 46), (21, 47), (22, 0), (22, 1), (22, 2), (22, 3), (22, 4), (22, 5), (22, 6), (22, 7), (22, 8), (22, 9), (22, 12), (22, 13), (22, 14), (22, 15), (22, 16), (22, 17), (22, 18), (22, 19), (22, 10), (22, 11), (22, 29), (22, 30), (22, 31), (22, 32), (22, 33), (22, 34), (22, 35), (22, 36), (22, 37), (22, 38), (22, 39), (22, 40), (22, 41), (22, 42), (22, 43), (22, 48), (22, 49), (22, 44), (22, 45), (22, 46), (22, 47), (23, 0), (23, 1), (23, 2), (23, 3), (23, 4), (23, 5), (23, 6), (23, 7), (23, 8), (23, 9), (23, 12), (23, 13), (23, 14), (23, 15), (23

In [19]:
A = nx.adjacency_matrix(G)

In [23]:
A.todence()

AttributeError: todence not found

In [24]:
for line in nx.generate_adjlist(G):
    print(line)

0 21 22 23 24 25 26
21 0 1 2 3 4 5 6 7 8 9 12 13 14 15 16 17 18 19 10 11 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 48 49 44 45 46 47
22 0 1 2 3 4 5 6 7 8 9 12 13 14 15 16 17 18 19 10 11 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 48 49 44 45 46 47
23 0 1 2 3 4 5 6 7 8 9 12 13 14 15 16 17 18 19 10 11 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 48 49 44 45 46 47
24 0 1 2 3 4 5 6 7 8 9 12 13 14 15 16 17 18 19 10 11 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 48 49 44 45 46 47
25 0 1 2 3 4 5 6 7 8 9 12 13 14 15 16 17 18 19 10 11 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 48 49 44 45 46 47
26 0 1 2 3 4 5 6 7 8 9 12 13 14 15 16 17 18 19 10 11 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 48 49 44 45 46 47
1 21 22 23 24 25 26
2 21 22 23 24 25 26
3 21 22 23 24 25 26
4 21 22 23 24 25 26 10 11
5 21 22 23 24 25 26 10 11
6 21 22 23 24 25 26 10 11
7 21 22 23 24 25 26 10 11
8 21 22 23 24 25 26 10 11
9 21 22 23 24 25 26 10 11
12 21 22 23 24 25 26 10 11
13 21 22 23 24 25 26 10 11
14 21 22 23 24

In [27]:
nx.write_adjlist(G, 'DatasetUpdate')

PermissionError: [Errno 13] Permission denied: 'DatasetUpdate'